language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Kornev_AllLabs
  - make -j
  - ./StackTest/StackTest
  - ./Stack/Stack
  - ./QueueTest/QueueTest
  - ./Queue/Queue
  - ./VectorTest/VectorTest
  - ./Vector/Vector    
  - ./MatrixTest/MatrixTest
  - ./Matrix/Matrix   
  - ./ListTest/ListTest
  - ./List/List     
notifications:
  email: false
