language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Alllabs_Suslov
  - make -j
  - ./Vector/Vector
  - ./VectorTest/VectorTest
  - ./Stack/Stack
  - ./StackTest/StackTest
  - ./Queue/Queue
  - ./QueueTest/QueueTest
  - ./Matrix/Matrix
  - ./MatrixTest/MatrixTest
notifications:
  email: false
