language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Alllabs_Suslov
  - make -j
  - ./VectorTest/VectorTest
  - ./MatrixTest/MatrixTest
  - ./StackTest/StackTest
  - ./QueueTest/QueueTest
  - ./ListTest/ListTest
  - ./StackListTest/StackListTest
  - ./ArrayListTest/ArrayListTest
  - ./MultiStackTest/MultiStackTest
  - ./PolynomialTest/PolynomialTest
  - ./PolishTest/PolishTest
 #- ./TextTest/TextTest
  #- ./Text/Text
  - ./ScanTableTest/ScanTableTest
  - ./SortTableTest/SortTableTest
  - ./TreeTableTest/TreeTableTest
  - ./HashTableTest/HashTableTest
 
notifications:
  email: false
