language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Kornev_AllLabs
  - make -j
  - ./StackTest/StackTest
notifications:
  email: false
