language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Kornev_AllLabs
  - make -j
  - ./StackTest/StackTest
  - ./Stack/Stack
  - ./QueueTest/QueueTest
  - ./Queue/Queue
notifications:
  email: false
